version: '3.8'
services:
  app1:
      build: ./src
      tty: true
      volumes:
        - './app/src:/app/aspnetapp'
  app2:
      build: ./src
      tty: true
      volumes:
        - './app/src:/app/aspnetapp'
  loadbalancer:
      build: ./loadbalancer
      tty: true
      links:
          - app1
          - app2
      ports:
          - '8080:80'